### ISSUE TITLE
omits fail-fast setting

### ISSUE THREAD

**Issue by ljharb** [fregante/ghat#25]
I ran `npx ghat es-shims/Array.prototype.entries` inside https://github.com/es-shims/Object.getPrototypeOf and it did not copy over the `fail-fast: false` setting.

This persisted even with `--verbatim`.

**Comment by fregante** [comment]
I don't see any `fail-fast` in files in https://github.com/es-shims/Array.prototype.entries/tree/main/.github/workflows 🤔

**Comment by ljharb** [comment]
ahhhh yes, those changes are local on my machine but not pushed up to the repo (－‸ლ) my bad!
