### ISSUE TITLE
Implemented by GitHub?

### ISSUE THREAD

**Issue by kidonng** [fregante/ghat#30]
https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/

**Comment by fregante** [comment]
Nope, that only allows you to wrap multiple actions into one, but not manage whole workflows. Also said multiple actions will appear as a single step, stop all-around _not great_

**Comment by fregante** [comment]
See this workflow run using the example composed action from their docs:

<img width="433" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/130952842-1884aa41-71a3-4a0b-a748-51083850d967.png">

"octocat" and "goodbye" are 2 separate steps but appear as one: the parent.

https://github.com/fregante/sandbox/runs/3429229050?check_suite_focus=true
